// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/psqlqueue/domain"
	mock "github.com/stretchr/testify/mock"
)

// MessageService is an autogenerated mock type for the MessageService type
type MessageService struct {
	mock.Mock
}

// Ack provides a mock function with given fields: ctx, id
func (_m *MessageService) Ack(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, message
func (_m *MessageService) Create(ctx context.Context, message *domain.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, queueID, label, limit
func (_m *MessageService) List(ctx context.Context, queueID string, label *string, limit uint) ([]*domain.Message, error) {
	ret := _m.Called(ctx, queueID, label, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, uint) ([]*domain.Message, error)); ok {
		return rf(ctx, queueID, label, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, uint) []*domain.Message); ok {
		r0 = rf(ctx, queueID, label, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, uint) error); ok {
		r1 = rf(ctx, queueID, label, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Nack provides a mock function with given fields: ctx, id, visibilityTimeoutSeconds
func (_m *MessageService) Nack(ctx context.Context, id string, visibilityTimeoutSeconds uint) error {
	ret := _m.Called(ctx, id, visibilityTimeoutSeconds)

	if len(ret) == 0 {
		panic("no return value specified for Nack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) error); ok {
		r0 = rf(ctx, id, visibilityTimeoutSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessageService creates a new instance of MessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageService {
	mock := &MessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
